./setup_db.sh
sleep 6

./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test
./mvnw clean test



